# Generated by Django 4.2.18 on 2025-06-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='dis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
